configs: crystal_defconfig: set USB configs via savedefconfig
CMD_USB needed to repair following build error

In file included from include/configs/crystal.h:102,
                 from include/config.h:4,
                 from include/common.h:16,
                 from env/common.c:10:
include/config_distro_bootcmd.h:292:2: error: expected ‘}’ before
‘BOOT_TARGET_DEVICES_references_USB_without_CONFIG_CMD_USB’
  292 |  BOOT_TARGET_DEVICES_references_USB_without_CONFIG_CMD_USB
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/config_distro_bootcmd.h:292:2: note: in definition of macro
‘BOOTENV_DEV_NAME_USB’
  292 |  BOOT_TARGET_DEVICES_references_USB_without_CONFIG_CMD_USB
      |  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Tomasz Żyjewski <tomasz.zyjewski@3mdeb.com>